### ISSUE TITLE
About the file 'checkpoint.tar'

### ISSUE THREAD

**Issue by LingZhangA** [ksolaiman/TransAE#3]
Thank you for the code. But when I ran the main.py, the error told me that No such file or diectory: 'checkpoint.tar', and I didn't found the file in the code that you provided. Hope you can give an answer, thanks.

**Comment by LingZhangA** [comment]
I got it.

**Comment by qixiaonan12** [comment]
> I got it.

hello！May I ask that you have not encountered the following problems, which makes me unable to run through the whole program
Traceback (most recent call last):
  File "main.py", line 248, in <module>
    app.run(main)
  File "/root/miniconda3/lib/python3.7/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/root/miniconda3/lib/python3.7/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "main.py", line 230, in main
    epoch_id=epoch_id, metric_suffix="val")
  File "main.py", line 72, in test
    tails_predictions = model.predict(triplets).reshape(current_batch_size, -1)
  File "/root/autodl-tmp/TransAE-master/TransE-PyTorch-master/model.py", line 266, in predict
    return self._distance(triplets)[0]
  File "/root/autodl-tmp/TransAE-master/TransE-PyTorch-master/model.py", line 278, in _distance
    v3_h, recon_loss_h = self.autoencoder(heads) 
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/autodl-tmp/TransAE-master/TransE-PyTorch-master/model.py", line 177, in forward
    v5_i = self.decoder_visual_linear2(v4_i)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 204, in forward
    input = module(input)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.7/site-packages/torch/nn/modules/activation.py", line 294, in forward
    return torch.sigmoid(input)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 6.40 GiB (GPU 0; 23.70 GiB total capacity; 16.01 GiB already allocated; 5.85 GiB free; 16.74 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
